services:
  traefik:
    image: traefik:v2.11
    environment:
      - GANDIV5_PERSONAL_ACCESS_TOKEN_FILE=/run/secrets/gandiv5_personal_access_token
    volumes:
      - $PWD/traefik.yaml:/etc/traefik/traefik.yaml
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_letsencrypt_cache:/etc/traefik/acme
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    secrets:
      - "gandiv5_personal_access_token"

  whoami:
    image: traefik/whoami

secrets:
  gandiv5_personal_access_token:
    file: ./secrets/gandi-v5-token.secret

volumes:
  traefik_letsencrypt_cache: {}
