services:
  traefik:
    image: traefik:v2.5
    volumes:
      - $PWD/traefik.yaml:/etc/traefik/traefik.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "80:80"
