version: "3.8"
services:
  server:
    image: gitea/gitea:1.21.11
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__DOMAIN=gitea.aredherring.tech
      - GITEA__server__ROOT_URL=https://gitea.aredherring.tech
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD__FILE=/run/secrets/gitea_password.v1
      - GITEA__service__ALLOW_ONLY_EXTERNAL_REGISTRATION=true
      - GITEA__openid__ENABLE_OPENID_SIGNIN=true
      - GITEA__openid__ENABLE_OPENID_SIGNUP=true
      - GITEA__openid__WHITELISTED_URIS=https://sso.aredherring.tech/
    networks:
      - gitea
      - traefik
    volumes:
      - /data
    secrets:
      - gitea_password.v1
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.gitea.rule=Host(`gitea.aredherring.tech`)
        - traefik.http.routers.gitea.service=gitea
        - traefik.http.routers.gitea.tls.certresolver=letsencrypt
        - traefik.http.services.gitea.loadbalancer.server.port=3000
        - traefik.tcp.routers.gitea-ssh.rule=HostSNI(`*`)
        - traefik.tcp.routers.gitea-ssh.entrypoints=ssh
        - traefik.tcp.routers.gitea-ssh.service=gitea-ssh
        - traefik.tcp.services.gitea-ssh.loadbalancer.server.port=22

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: gitea
      POSTGRES_USER: gitea
      POSTGRES_PASSWORD_FILE: /run/secrets/gitea_password.v1
    secrets:
      - gitea_password.v1
    volumes:
      - /var/lib/postgresql
    networks:
      - gitea

secrets:
  gitea_password.v1:
    file: ./secrets/gitea_postgres_password.txt

networks:
  gitea: {}
  traefik:
    name: traefik_services
    external: true
