version: "3.8"
services:
  server:
    image: gitea/gitea:1.21.11
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__DOMAIN=gitea.aredherring.tech
      - GITEA__server__ROOT_URL=https://gitea.aredherring.tech
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD__FILE=/run/secrets/gitea_password.v1
      - GITEA__service__ALLOW_ONLY_EXTERNAL_REGISTRATION=true
      - GITEA__openid__ENABLE_OPENID_SIGNIN=true
      - GITEA__openid__ENABLE_OPENID_SIGNUP=true
      - GITEA__openid__WHITELISTED_URIS=https://sso.aredherring.tech/
    networks:
      - gitea
      - traefik
    volumes:
      - gitea:/data
    secrets:
      - gitea_password.v1
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.gitea.rule=Host(`gitea.aredherring.tech`)
        - traefik.http.routers.gitea.service=gitea
        - traefik.http.routers.gitea.tls.certresolver=letsencrypt
        - traefik.http.services.gitea.loadbalancer.server.port=3000
        - traefik.tcp.routers.gitea-ssh.rule=HostSNI(`*`)
        - traefik.tcp.routers.gitea-ssh.entrypoints=ssh
        - traefik.tcp.routers.gitea-ssh.service=gitea-ssh
        - traefik.tcp.services.gitea-ssh.loadbalancer.server.port=22

  runners:
    image: gitea/act_runner:latest
    environment:
      - CONFIG_FILE=/etc/config.yaml
      - GITEA_INSTANCE_URL=https://gitea.aredherring.tech
      - GITEA_TOKEN_FILE=/run/secrets/gitea_token.v1
      - GITEA_RUNNER_REGISTRATION_TOKEN_FILE=/run/secrets/gitea_runner_token.v1
    configs:
      - source: gitea-runner.v1
        target: /etc/config.yaml
    secrets:
      - gitea_runner_token.v1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data
    deploy:
      replicas: 3

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: gitea
      POSTGRES_USER: gitea
      POSTGRES_PASSWORD_FILE: /run/secrets/gitea_password.v1
    secrets:
      - gitea_password.v1
    volumes:
      - /var/lib/postgresql
    networks:
      - gitea

configs:
  gitea-runner.v1:
    file: ./configs/gitea/ci.yaml

secrets:
  gitea_password.v1:
    file: ./secrets/gitea_postgres_password.txt
  gitea_runner_token.v1:
    file: ./secrets/gitea/ci_runner_token.txt

volumes:
  gitea: {}

networks:
  gitea: {}
  traefik:
    name: traefik_services
    external: true
  vault:
    external: true
    name: vault