version: "3.8"
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - "8081:80"
      - "2222:22"
    volumes:
      - /var/opt/gitlab
      - /var/log/gitlab
      - /etc/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['omniauth_auto_sign_in_with_provider'] = 'openid_connect'
        gitlab_rails['omniauth_providers'] = [
          {
            name: "openid_connect",
            label: "Keycloak",
            args: {
              name: "openid_connect",
              scope: ["openid", "email", "profile"],
              response_type: "code",
              issuer: "http://192.168.0.215:8080/auth/realms/gitlab",
              discovery: true,
              client_auth_method: "query",
              uid_field: "preferred_username",
              send_scope_to_token_endpoint: true,
              pkce: true,
              client_options: {
                identifier: "gitlab",
                redirect_uri: "http://localhost:8081/users/auth/openid_connect/callback",
              }
            }
          }
        ]

