# Keycloak is in its own stack so that other services can reference it from localhost or via a domain name using the host network. Discovery becomes difficult otherwise.
version: "3.8"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password.v1
    secrets:
      - postgres_password.v1
    networks:
      - database

  keycloak:
    image: registry.aredherring.tech/keycloak:latest
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: "5432"
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD_FILE: /run/secrets/postgres_password.v1
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD_FILE: /run/secrets/admin_password.v1
    ports:
      - "8080:8080"
    networks:
      - database
    secrets:
      - postgres_password.v1
      - admin_password.v1
    command: start-dev

secrets:
  postgres_password.v1:
    file: ./secrets/keycloak_pg_password.txt
  admin_password.v1:
    file: ./secrets/keycloak_admin_password.txt

networks:
  database: {}
