version: "3.8"
services:
  openbao:
    image: openbao/openbao:latest
    networks:
      - openbao
    deploy:
      replicas: 5

networks:
  openbao:
    # This is an external network that can be used to allow connections to Openbao for our internal services to go through our private network, rather than needing to go over the internet.
    external: true
    name: openbao
