# This stack contains core services required to run Traefik and to check that it is working correctly.
services:
  traefik:
    image: traefik:v2.11
    environment:
      - GANDIV5_PERSONAL_ACCESS_TOKEN_FILE=/run/secrets/gandiv5_personal_access_token
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_letsencrypt_cache:/etc/traefik/acme
    ports:
      - "443:443"
      - "8080:8080"
    secrets:
      - "gandiv5_personal_access_token"
    configs:
      - source: traefik
        target: /etc/traefik/traefik.yaml
    labels:
      traefik.enabled: "false"

  whoami:
    image: traefik/whoami
    labels:
      traefik.http.routers.whoami.rule: Host(`whoami.aredherring.tech`)
      traefik.http.routers.whoami.entrypoints: websecure
    deploy:
      replicas: 2

secrets:
  gandiv5_personal_access_token:
    file: ./secrets/gandi-v5-token.secret

volumes:
  traefik_letsencrypt_cache: {}

configs:
  traefik:
    file: ./traefik.yaml
