# Traefik is used to reverse-proxy to our services.
# This is necessary because services really need to be able to reach Keycloak using a domain name, rather than using `localhost`.
version: "3.8"
services:
  traefik:
    image: traefik:v3.0.0
    environment:
      # This is required to verify DNS records with Gandi.
      GANDIV5_PERSONAL_ACCESS_TOKEN_FILE: /run/secrets/gandi-api-key
    ports:
      - "443:443"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/traefik/acme
    configs:
      - source: traefik.v9
        target: /etc/traefik/traefik.yaml
    networks:
      - traefik
    secrets:
      - gandi-api-key

secrets:
  gandi-api-key:
    file: secrets/gandi_api_key.txt

configs:
  traefik.v9:
    file: configs/traefik/traefik.yaml

networks:
  traefik:
    external: true
    name: traefik_services