## traefik.yml

# Docker configuration backend
providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.aredherring.tech`)"

# API and dashboard configuration
api:
  insecure: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: "dan@aredherring.tech"
      storage: "/letsencrypt/acme.json"
      # Experimental server with lower rate limits.
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: "gandiv5"
        delayBeforeCheck: 0

entryPoints:
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt

log:
  level: DEBUG
