providers:
  swarm:
    exposedByDefault: false
    network: traefik_services

entryPoints:
  websecure:
    address: ":443"
    asDefault: true
  # This is enabled for Gitea
  ssh:
    address: ":22"

log:
  level: INFO

certificatesResolvers:
  letsencrypt:
    acme:
      email: dan@aredherring.tech
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: gandiv5
