name: ci
on:
  push:
    branches:
      - main

jobs:
  Build-Images:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build images
        run: ./build-images.sh

  Userland-Stack-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Deploy all stacks
        run: |
          for STACK_FILE in $(find userland/stacks -type f -name stack.yaml); do
            DIR=$(dirname $STACK_FILE .yaml)
            STACK_NAME=$(basename $DIR)
            docker stack deploy "$STACK_NAME" --compose-file="$STACK_FILE"
          done
