version: "3.8"
services:
  vault:
    image: registry.aredherring.tech/vault:latest
    networks:
      - vault
      - traefik
      - stats
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_API_ADDR: https://vault.aredherring.tech:8200
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.vault.rule=Host(`vault.aredherring.tech`)"
        - "traefik.http.routers.vault.entrypoints=websecure"
        - "traefik.http.routers.vault.tls=true"
        - "traefik.http.routers.vault.tls.certresolver=letsencrypt"
        - "traefik.http.services.vault.loadbalancer.server.port=8200"
    configs:
      - source: vault_config.v8
        target: /vault/config/server.hcl
    volumes:
      - vault_data:/var/raft/
    # This command is here to disable dev mode.
    command: server -config=/vault/config/server.hcl
  statsd:
    image: statsd/statsd:latest
    networks:
      - stats

volumes:
  vault_data: {}

configs:
  vault_config.v8:
    file: ./server.hcl

networks:
  stats: {}
  vault:
    # This is an external network that can be used to allow connections to Openbao for our internal services to go through our private network, rather than needing to go over the internet.
    external: true
    name: vault
  traefik:
    external: true
    name: traefik_services
