providers:
  swarm:
    exposedByDefault: false
    network: traefik_services

entryPoints:
  websecure:
    address: ":443"
    asDefault: true
  # This is enabled for Gitea
  ssh:
    address: ":22"

log:
  level: INFO

certificatesResolvers:
  letsencrypt:
    acme:
      storage: /etc/traefik/acme/acme.json
      email: dan@aredherring.tech
      # Enable this if the server starts flapping to prevent us being rate-limited from getting certs.
      # Certs are stored in a Docker volume so this isn't really going to be a problem anyway.
      # caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: gandiv5
